repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - id: uv-lock
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  # - repo: local
    # hooks:
    #   - id: pytest
    #     name: pytest
    #     entry: ./.venv/bin/pytest tests
    #     language: python
    #     pass_filenames: false
    #     always_run: true